name: Docker Image CI
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          submodules: recursive
      - name: Docker Build
        run: |
          docker build --file Dockerfile .
        if: github.ref != 'refs/heads/master'
      - name: Push image on repo
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: polycubenets/polycube-codegen
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'
